import { readdirSync, writeFileSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const header = "//This file is auto-generated by running `lib/findIcons.js`. Please do not edit it manually.\n";
const resolve = (path) => fileURLToPath(import.meta.resolve(path));
const icons = readdirSync(resolve("../app/assets/images/icons/")).flatMap(
  (name) => name.slice(0, -path.extname(name).length) || [],
);

const brands = readdirSync(resolve("../app/assets/images/brands/")).flatMap(
  (name) => name.slice(0, -path.extname(name).length) || [],
);

const jsonContent = JSON.stringify(
  Object.fromEntries([
    ...icons.map((icon) => [icon, `mask-[url(~images/icons/${icon}.svg)]`]),
    ...brands.map((brand) => [`brand-${brand}`, `mask-[url(~images/brands/${brand}.svg)]`]),
  ]),
  null,
  2,
);

writeFileSync(resolve("../app/javascript/data/icons.json"), jsonContent);

const tsContent = `${header}
export const iconClasses = ${jsonContent};
export type IconName = keyof typeof iconClasses;
`;

writeFileSync(resolve("../app/javascript/data/generated-icons.ts"), tsContent);
